### ISSUE TITLE
ERR: module for custom nodes: No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by Duemellon** [ArcherFMY/Diffusion360_ComfyUI#7]
Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Diffusion360_ComfyUI module for custom nodes: No module named 'torchvision.transforms.functional_tensor'
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
E:\ComfyUI_windows_portable\ComfyUI\web\extensions\failfast-comfyui-extensions
Downloading anime face detector...
Failed to download lbpcascade_animeface.xml so please download it in E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI.
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data

**Comment by ArcherFMY** [comment]
hi，same issue here https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985

**Comment by GTARandom** [comment]
I found a way to get rid of this error and get this working on my end. Another error had popped up later, I had to deal with another error afterwards (described in text details below), that's been solved too. 

**So for the first one:**

This is how the error was removed (below is a quote from Known Problems section of the Git repo of **RealESRGAN_Upscaler**, author **zentrocdot**: https://github.com/zentrocdot/ComfyUI-RealESRGAN_Upscaler

```
Fix for the moment is as follows. Go into directory ComfyUI. Then search for a file.

find -name "degradations.py"

This looks like.

./venv/lib/python3.10/site-packages/basicsr/data/degradations.py

Open the file e.g.

nano ./venv/lib/python3.10/site-packages/basicsr/data/degradations.py

and change

from torchvision.transforms.functional_tensor import rgb_to_grayscale

to

from torchvision.transforms.functional import rgb_to_grayscale

After that, the node will work.

```

~~
Error that resulted after that is this:   

```
_pickle.UnpicklingError: Weights only load failed. In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
Please file an issue with the following so that we can make `weights_only=True` compatible with your use case: WeightsUnpickler error: Unsupported operand 60


Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html
```
~~

Second error has been resolved by redownloading the HuggingFace model properly into the models/diffusers folder of ComfyUI from: https://huggingface.co/archerfmy0831/sd-t2i-360panoimage and renaming the download to diffusion360.

I suggest using this command from within diffusers folder to download entire model and not miss anything that may be important:

`git lfs clone https://huggingface.co/archerfmy0831/sd-t2i-360panoimage`

It's important to use lfs (large file storage) so that everything gets downloaded correctly.

Hoping this will help someone! - proof that it works is attached to this post.

<img width="2121" height="492" alt="Image" src="https://github.com/user-attachments/assets/97b691de-2f51-423a-9a93-ecd3bb7423b9" />
